# Generated by Django 3.1.13 on 2022-01-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='id_index',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pricee',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
